---
name: Build and Publish

on:
  push:
    branches:
      - buildme-**

jobs:
  build-and-publish:
    name: Publish container image
    env:
      BRANCH_PREFIX: buildme- # IMPORTANT! this must match the .on.push.branches prefix!
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Echo branch name
        run: echo ${GITHUB_REF#refs/heads/}

      - name: Set version from branch name
        if: startsWith('env.BRANCH_PREFIX', env.GITHUB_REF)
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "::set-output name=version::${BRANCH_NAME/${{ env.BRANCH_PREFIX }}/}"
        id: version-from-branch

      - name: Echo version from branch
        if: startsWith('env.BRANCH_PREFIX', env.GITHUB_REF)
        run: echo "The version is ${{ steps.version-from-branch.outputs.version }}"

      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

          # - name: Build and push
          #   id: docker_build
          #   uses: docker/build-push-action@v2
          #   with:
          #     push: true
          #     tags: quay.io/projectquay/quay:3.5
